apiVersion: v1
kind: Pod
metadata:
  name: devops-001-hello
  labels:
    name: devops-001-hello
    type: backend
    app: hello-service
    project-name: mydemo

spec:
  containers:
    - name: devops-001-hello
      image: kubrakosee/devops-001-hello:v001
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Pod
metadata:
  name: my-new-pod2
  labels:
    name: my-new-pod2
    type: front
    app: mydemo2-service
    project-name: mydemo

spec:
  containers:
    - name: my-new-pod2
      image: kubrakosee/devops-001-hello:v002
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 9091
